[core]
workspace_base="./workspace"

[llm]
model="meta-llama/Llama-3.1-405B"
api_key="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"
base_url="https://api-inference.huggingface.co/models/meta-llama/Llama-3.1-405B"
embedding_model="bge-large"
